name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/bigbadjock/index.json
      env: 
         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
     
    - name: Install dependencies
      run: dotnet restore ./REST-Parser/REST-Parser.sln
    - name: Build
      run: dotnet build ./REST-Parser/REST-Parser.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./REST-Parser/REST-Parser.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack ./REST-Parser/REST-Parser.sln --configuration Release -o out --no-build
    - name: Add GPR source
      run: nuget sources Add -Name "GPR" -Source ${{ secrets.GPR_URI }} -UserName {{ GPR_USERNAME }} -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./REST-Parser/out/*.nupkg  -Source "GPR" --skip-duplicate --no-symbols true

